;;; qq-group-test.el --- Tests for qq-group -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'qq-group)
(require 'qq-chat)
(require 'qq-root)

(defconst qq-group-test--profile
  '((group_id . "20001")
    (name . "Emacs Users")
    (remark . "Work")
    (description . "Talk about Emacs")
    (announcement . "Read the rules")
    (owner_id . "10001")
    (member_count . 42)
    (max_member_count . 500)
    (active_member_count . 12)
    (created_at . 1000)
    (joined_at . 2000)
    (pinned . t)
    (mute . ((all_until) (self_until . 3000)))
    (join . ((mode . "question_answer")
             (mode_code . 4) (question . "Editor?") (answer)))
    (self_permission . "member")
    (self_permission_code . 2)
    (category . ((code . 7) (name . "Technology")))
    (grade . 3)
    (certification . ((type_code . 1) (text . "Official")))
    (school . ((location . "Shanghai") (grade_code . 2) (name . "Example")))
    (location . ((text . "Shanghai") (latitude . "31.2") (longitude . "121.5")))
    (has_custom_avatar . t))
  "One complete native group profile fixture.")

(ert-deftest qq-api-get-group-preserves-string-identity ()
  (let (action params value)
    (cl-letf (((symbol-function 'qq-api-call)
               (lambda (candidate-action candidate-params callback
                        &optional _errback)
                 (setq action candidate-action
                       params candidate-params)
                 (funcall callback `((data . ,qq-group-test--profile)))
                 'request)))
      (should (eq (qq-api-get-group "20001" (lambda (profile)
                                                (setq value profile)))
                  'request))
      (should (equal action "emacs_get_group"))
      (should (equal params '((group_id . "20001"))))
      (should (equal (alist-get 'group_id value) "20001"))
      (should-error (qq-api-get-group 20001 #'ignore) :type 'user-error))))

(ert-deftest qq-group-render-shows-telega-style-card ()
  (with-temp-buffer
    (qq-group-mode)
    (setq qq-group--group-id "20001"
          qq-group--profile (copy-tree qq-group-test--profile))
    (cl-letf (((symbol-function 'qq-media-group-avatar-display-string)
               (lambda (_group-id) "@")))
      (qq-group-render))
    (let ((text (buffer-string)))
      (should (string-match-p "Work" text))
      (should (string-match-p "群号:[[:space:]]+20001" text))
      (should (string-match-p "成员:[[:space:]]+42 / 500" text))
      (should (string-match-p "群主:[[:space:]]+10001" text))
      (should (string-match-p "群分类:[[:space:]]+Technology" text))
      (should (string-match-p "我的权限:[[:space:]]+成员" text))
      (should (string-match-p "入群模式:[[:space:]]+需正确回答问题" text))
      (should (string-match-p "认证:[[:space:]]+Official" text))
      (should-not (string-match-p "code [0-9]" text))
      (should (string-match-p "Talk about Emacs" text))
      (should (string-match-p "Read the rules" text))
      (should-not (string-match-p "\\[Open\\]" text))
      (goto-char (point-min))
      (search-forward "打开群聊")
      (should (button-at (1- (point)))))))

(ert-deftest qq-group-render-omits-unresolved-raw-enums ()
  (with-temp-buffer
    (qq-group-mode)
    (setq qq-group--group-id "20001"
          qq-group--profile
          '((group_id . "20001") (name . "Unknowns")
            (owner_id) (member_count . 1) (max_member_count . 1)
            (join . ((mode) (mode_code . 99)))
            (self_permission) (self_permission_code . 99)
            (category . ((code . 34) (name)))
            (certification . ((type_code . 99) (text)))))
    (cl-letf (((symbol-function 'qq-media-group-avatar-display-string)
               (lambda (_group-id) "@")))
      (qq-group-render))
    (let ((text (buffer-string)))
      (should-not (string-match-p "code [0-9]" text))
      (should-not (string-match-p "我的权限:" text))
      (should-not (string-match-p "入群模式:" text))
      (should-not (string-match-p "群分类:" text))
      (should-not (string-match-p "认证:" text)))))

(ert-deftest qq-group-refresh-handles-synchronous-response-ownership ()
  (with-temp-buffer
    (qq-group-mode)
    (setq qq-group--group-id "20001")
    (cl-letf (((symbol-function 'qq-group-render) #'ignore)
              ((symbol-function 'qq-api-get-group)
               (lambda (_group-id callback &optional _errback)
                 (funcall callback (copy-tree qq-group-test--profile))
                 'request)))
      (qq-group-refresh)
      (should (equal qq-group--profile qq-group-test--profile))
      (should-not qq-group--loading)
      (should-not qq-group--request)
      (should-not qq-group--request-owner))))

(ert-deftest qq-group-entry-commands-dispatch-by-session-type ()
  (let (opened-user opened-group)
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . group) (target-id . "20001"))))
              ((symbol-function 'qq-group-open)
               (lambda (group-id) (setq opened-group group-id))))
      (qq-root-open-info-at-point)
      (should (equal opened-group "20001")))
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . private)
                            (target-id . "10001")
                            (peer-uin . "10001"))))
              ((symbol-function 'qq-user-open)
               (lambda (user-id) (setq opened-user user-id))))
      (qq-root-open-info-at-point)
      (should (equal opened-user "10001")))))

(ert-deftest qq-group-entry-keymaps-match-chat-info-conventions ()
  (should (eq (lookup-key qq-root-mode-map (kbd "i"))
              #'qq-root-open-info-at-point))
  (should (eq (lookup-key qq-chat-timeline-mode-map (kbd "h"))
              #'qq-chat-open-peer-info))
  (should (eq (lookup-key qq-chat-mode-map (kbd "C-c i"))
              #'qq-chat-open-peer-info))
  (should (eq (lookup-key qq-group-mode-map (kbd "m"))
              #'qq-group-open-chat)))

(ert-deftest qq-group-reuses-one-profile-buffer-like-telega ()
  (should (equal (qq-group--buffer-name "20001") "*qq-group*"))
  (should (equal (qq-group--buffer-name "20002") "*qq-group*")))

(provide 'qq-group-test)

;;; qq-group-test.el ends here
