;;; qq-state-test.el --- Tests for qq-state -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'qq-state)

(defmacro qq-test-with-reset (&rest body)
  "Run BODY with a clean in-memory qq-state store."
  `(let ((qq-state-change-hook nil))
     (qq-state-reset)
     (unwind-protect
         (progn ,@body)
       (qq-state-reset))))

(ert-deftest qq-state-session-key-normalizes-type-and-id ()
  (qq-test-with-reset
   (should (equal (qq-state-session-key 'private 12345)
                  "private:12345"))
   (should (equal (qq-state-session-key 'group "67890")
                  "group:67890"))
   (should (equal (qq-state-session-key 'dataline "device-1")
                  "dataline:device-1"))))

(ert-deftest qq-state-apply-recent-contacts-creates-session-summary ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 1)
       (peerUin . "10001")
       (remark . "Alice")
       (peerName . "Alice Nick")
       (msgTime . "1710000000")
       (msgId . "42")
       (lastestMsg
        (time . 1710000000)
        (message_type . "private")
        (user_id . 10001)
        (raw_message . "hello from napcat")
        (message . (((type . "text")
                     (data . ((text . "hello from napcat"))))))))))
   (let ((session (qq-state-session "private:10001")))
     (should (equal (alist-get 'title session) "Alice"))
     (should (equal (alist-get 'last-message-id session) "42"))
     (should (equal (alist-get 'last-message-preview session)
                    "hello from napcat")))))

(ert-deftest qq-state-apply-recent-contacts-keeps-dataline-sessions-distinct ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 8)
       (peerUid . "device-1")
       (peerUin . "0")
       (remark . "")
       (peerName . "")
       (msgTime . "1710000000")
       (msgId . "42")
       (lastestMsg
        (time . 1710000000)
        (message_type . "private")
        (chat_type . 8)
        (peer_uid . "device-1")
        (peer_uin . "0")
        (user_id . 0)
        (sender . ((user_id . 0)
                   (nickname . "我的手机")))
        (raw_message . "hello from phone")
        (message . (((type . "text")
                     (data . ((text . "hello from phone"))))))))
      ((chatType . 8)
       (peerUid . "device-2")
       (peerUin . "0")
       (remark . "")
       (peerName . "")
       (msgTime . "1710000001")
       (msgId . "43")
       (lastestMsg
        (time . 1710000001)
        (message_type . "private")
        (chat_type . 8)
        (peer_uid . "device-2")
        (peer_uin . "0")
        (user_id . 0)
        (sender . ((user_id . 0)
                   (nickname . "我的手机")))
        (raw_message . "second device")
        (message . (((type . "text")
                     (data . ((text . "second device"))))))))))
   (let ((session-1 (qq-state-session "dataline:device-1"))
         (session-2 (qq-state-session "dataline:device-2")))
     (should (equal (alist-get 'title session-1) "我的手机"))
     (should (equal (alist-get 'title session-2) "我的手机"))
     (should (equal (alist-get 'peer-uid session-1) "device-1"))
     (should (equal (alist-get 'peer-uid session-2) "device-2"))
     (should (equal (alist-get 'last-message-preview session-1) "hello from phone"))
     (should (equal (alist-get 'last-message-preview session-2) "second device")))))

(ert-deftest qq-state-send-pending-message-transitions-to-sent ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-upsert-session "private:10001" '((title . "Alice")) nil)
   (let* ((pending (qq-state-insert-pending-text-message "private:10001" "ping"))
          (local-id (alist-get 'local-id pending)))
     (qq-state-mark-pending-message-sent "private:10001" local-id 88)
     (let ((message (car (qq-state-session-messages "private:10001"))))
       (should (equal (alist-get 'server-id message) "88"))
       (should (eq (alist-get 'status message) 'sent))
       (should (equal (alist-get 'raw-message message) "ping"))))))

(ert-deftest qq-state-live-message-increments-unread-and-supports-recall ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (message_id . 123)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (nickname . "Alice")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((session (qq-state-session "private:10001")))
     (should (= (alist-get 'unread-count session) 1)))
   (qq-state-apply-recall 123)
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (eq (alist-get 'status message) 'recalled))
     (should (equal (alist-get 'raw-message message) "[message recalled]")))))

(ert-deftest qq-state-live-dataline-message-routes-by-peer-uid ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (chat_type . 8)
      (peer_uid . "device-1")
      (peer_uin . "0")
      (peer_name . "我的手机")
      (message_id . 123)
      (user_id . 0)
      (time . 1710000001)
      (sender . ((user_id . 0)
                 (nickname . "我的手机")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let* ((session (qq-state-session "dataline:device-1"))
          (message (car (qq-state-session-messages "dataline:device-1"))))
     (should (equal (alist-get 'title session) "我的手机"))
     (should (equal (alist-get 'sender-name message) "我的手机"))
     (should-not (alist-get 'self-p message))
     (should (= (alist-get 'unread-count session) 1)))))

(ert-deftest qq-state-live-message-ignores-empty-group-card-when-choosing-sender-name ()
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "group")
      (message_id . 123)
      (group_id . 20001)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (card . "")
                 (nickname . "Alice")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "group:20001"))))
     (should (equal (alist-get 'sender-name message) "Alice"))
     (should-not (alist-get 'sender-secondary-name message)))))

(ert-deftest qq-state-group-message-keeps-card-and-nickname-for-display ()
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "group")
      (message_id . 123)
      (group_id . 20001)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (card . "Alice Card")
                 (nickname . "Alice Nick")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "group:20001"))))
     (should (equal (alist-get 'sender-name message) "Alice Card"))
     (should (equal (alist-get 'sender-secondary-name message) "Alice Nick"))
     (should (equal (alist-get 'sender-card message) "Alice Card"))
     (should (equal (alist-get 'sender-nickname message) "Alice Nick")))))

(ert-deftest qq-state-private-message-prefers-remark-and-keeps-nickname-trail ()
  (qq-test-with-reset
   (qq-state-apply-friends
    '(((user_id . 10001)
       (remark . "Alice Remark")
       (nickname . "Alice Nick"))))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (message_id . 123)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (nickname . "Alice Nick")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (equal (alist-get 'sender-name message) "Alice Remark"))
     (should (equal (alist-get 'sender-secondary-name message) "Alice Nick"))
     (should (equal (alist-get 'sender-remark message) "Alice Remark"))
     (should (equal (alist-get 'sender-nickname message) "Alice Nick")))))

(ert-deftest qq-state-pending-message-ignores-empty-self-nickname ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "")))
   (let ((message (qq-state-insert-pending-text-message "private:10001" "ping")))
     (should (equal (alist-get 'sender-name message) "90001")))))

(ert-deftest qq-state-insert-pending-message-keeps-segments-and-preview ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-upsert-session "private:10001" '((title . "Alice")) nil)
   (let ((message (qq-state-insert-pending-message
                   "private:10001"
                   '(((type . "reply")
                      (data . ((id . "42"))))
                     ((type . "text")
                      (data . ((text . "hello")))))
                   "hello")))
     (should (equal (alist-get 'raw-message message) "hello"))
     (should (equal (alist-get 'preview message) "[reply]hello"))
     (should (equal (alist-get 'segments message)
                    '(((type . "reply")
                       (data . ((id . "42"))))
                      ((type . "text")
                       (data . ((text . "hello"))))))))))

(ert-deftest qq-state-set-status-deduplicates-identical-events ()
  (qq-test-with-reset
   (let (events)
     (add-hook 'qq-state-change-hook
               (lambda (event)
                 (when (eq (plist-get event :type) 'status)
                   (push event events))))
     (qq-state-set-status '((online . t)))
     (qq-state-set-status '((online . t)))
     (qq-state-set-status '((online . nil)))
     (should (= 2 (length events))))))

(provide 'qq-state-test)

;;; qq-state-test.el ends here
