;;; qq-state-test.el --- Tests for qq-state -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'qq-state)

(defmacro qq-test-with-reset (&rest body)
  "Run BODY with a clean in-memory qq-state store."
  `(let ((qq-state-change-hook nil))
     (qq-state-reset)
     (unwind-protect
         (progn ,@body)
       (qq-state-reset))))

(ert-deftest qq-state-session-key-normalizes-type-and-id ()
  (qq-test-with-reset
   (should (equal (qq-state-session-key 'private 12345)
                  "private:12345"))
   (should (equal (qq-state-session-key 'group "67890")
                  "group:67890"))
   (should (equal (qq-state-session-key 'dataline "device-1")
                  "dataline:device-1"))
   (should (equal (qq-state-session-key 'service "u_mail")
                  "service:u_mail"))))

(ert-deftest qq-state-apply-recent-contacts-creates-session-summary ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 1)
       (peerUin . "10001")
       (remark . "Alice")
       (peerName . "Alice Nick")
       (msgTime . "1710000000")
       (msgId . "42")
       (lastestMsg
        (time . 1710000000)
        (message_type . "private")
        (user_id . 10001)
        (raw_message . "hello from napcat")
        (message . (((type . "text")
                     (data . ((text . "hello from napcat"))))))))))
   (let ((session (qq-state-session "private:10001")))
     (should (equal (alist-get 'title session) "Alice"))
     (should (equal (alist-get 'last-message-id session) "42"))
     (should (equal (alist-get 'last-message-preview session)
                    "hello from napcat")))))

(ert-deftest qq-state-apply-recent-contacts-creates-service-session ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 103)
       (peerUid . "u_mail")
       (peerUin . "90002")
       (remark . "")
       (peerName . "QQ邮箱提醒")
       (msgTime . "1710000100")
       (msgId . "9007199254747004845")
       (lastestMsg
        (time . 1710000100)
        (message_type . "private")
        (chat_type . 103)
        (peer_uid . "u_mail")
        (peer_uin . "90002")
        (user_id . 90002)
        (sender . ((user_id . 90002)
                   (nickname . "QQ邮箱提醒")))
        (raw_message . "[CQ:mail]")
        (message . (((type . "mail")
                     (data . ((sender . "Henrik Lissner")
                              (subject . "Re: Doom Emacs")
                              (prompt . "Henrik Lissner: Re: Doom Emacs"))))))))))
   (let ((session (qq-state-session "service:u_mail")))
     (should (equal (alist-get 'title session) "QQ邮箱提醒"))
     (should (equal (alist-get 'type session) 'service))
     (should (equal (alist-get 'chat-type session) "103"))
     (should (equal (alist-get 'peer-uid session) "u_mail"))
     (should (equal (alist-get 'last-message-preview session)
                    "Henrik Lissner: Re: Doom Emacs")))))

(ert-deftest qq-state-apply-recent-contacts-keeps-dataline-sessions-distinct ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 8)
       (peerUid . "device-1")
       (peerUin . "0")
       (remark . "")
       (peerName . "")
       (msgTime . "1710000000")
       (msgId . "42")
       (lastestMsg
        (time . 1710000000)
        (message_type . "private")
        (chat_type . 8)
        (peer_uid . "device-1")
        (peer_uin . "0")
        (user_id . 0)
        (sender . ((user_id . 0)
                   (nickname . "我的手机")))
        (raw_message . "hello from phone")
        (message . (((type . "text")
                     (data . ((text . "hello from phone"))))))))
      ((chatType . 8)
       (peerUid . "device-2")
       (peerUin . "0")
       (remark . "")
       (peerName . "")
       (msgTime . "1710000001")
       (msgId . "43")
       (lastestMsg
        (time . 1710000001)
        (message_type . "private")
        (chat_type . 8)
        (peer_uid . "device-2")
        (peer_uin . "0")
        (user_id . 0)
        (sender . ((user_id . 0)
                   (nickname . "我的手机")))
        (raw_message . "second device")
        (message . (((type . "text")
                     (data . ((text . "second device"))))))))))
   (let ((session-1 (qq-state-session "dataline:device-1"))
         (session-2 (qq-state-session "dataline:device-2")))
     (should (equal (alist-get 'title session-1) "我的手机"))
     (should (equal (alist-get 'title session-2) "我的手机"))
     (should (equal (alist-get 'peer-uid session-1) "device-1"))
     (should (equal (alist-get 'peer-uid session-2) "device-2"))
     (should (equal (alist-get 'last-message-preview session-1) "hello from phone"))
     (should (equal (alist-get 'last-message-preview session-2) "second device")))))

(ert-deftest qq-state-send-pending-message-transitions-to-sent ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-upsert-session "private:10001" '((title . "Alice")) nil)
   (let* ((pending (qq-state-insert-pending-text-message "private:10001" "ping"))
          (local-id (alist-get 'local-id pending))
          ;; NapCat hard-cut: message_id is an NT snowflake string.
          (snowflake "9007199254741004645"))
     (qq-state-mark-pending-message-sent "private:10001" local-id snowflake)
     (let ((message (car (qq-state-session-messages "private:10001"))))
       (should (equal (alist-get 'server-id message) snowflake))
       (should (equal (alist-get 'id message) snowflake))
       (should (eq (alist-get 'status message) 'sent))
       (should (equal (alist-get 'raw-message message) "ping"))
       ;; Anchor prefers server snowflake after send.
       (should (equal (or (alist-get 'server-id message)
                          (alist-get 'local-id message))
                      snowflake))))))

(ert-deftest qq-state-live-message-increments-unread-and-supports-recall ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (message_id . "9007199254741004123")
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (nickname . "Alice")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((session (qq-state-session "private:10001")))
     (should (= (alist-get 'unread-count session) 1)))
   (qq-state-apply-recall "9007199254741004123")
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (qq-state-message-recalled-p message))
     (should (equal (alist-get 'preview message) "[message recalled]")))))

(ert-deftest qq-state-apply-recall-keeps-stub-in-store ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message_sent")
      (message_type . "private")
      (message_id . "9007199254741005555")
      (user_id . 90001)
      (target_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 90001)
                 (nickname . "Me")))
      (raw_message . "will recall")
      (message . (((type . "text")
                   (data . ((text . "will recall"))))))))
   (qq-state-apply-recall "9007199254741005555")
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (qq-state-message-recalled-p message))
     (should (equal (alist-get 'server-id message) "9007199254741005555")))))

(ert-deftest qq-state-napcat-recalled-flag-stores-stub ()
  "Protocol `recalled' stores a stub (display policy is chat's job)."
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (message_id . "9007199254741006666")
      (user_id . 10001)
      (time . 1710000001)
      (recalled . t)
      (recall_time . "1710000099")
      (sender . ((user_id . 10001)
                 (nickname . "Alice")))
      (raw_message . "")
      (message . ())))
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (qq-state-message-recalled-p message))
     (should (equal (alist-get 'preview message) "[message recalled]")))))

(ert-deftest qq-state-history-merge-preserves-recalled-status ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001) (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message_sent")
      (message_type . "private")
      (message_id . "9007199254741005555")
      (user_id . 90001)
      (target_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 90001) (nickname . "Me")))
      (raw_message . "x")
      (message . (((type . "text") (data . ((text . "x"))))))))
   (qq-state-apply-recall "9007199254741005555")
   (qq-state-merge-history
    "private:10001"
    (list
     '((post_type . "message_sent")
       (message_type . "private")
       (message_id . "9007199254741005555")
       (user_id . 90001)
       (target_id . 10001)
       (time . 1710000001)
       (sender . ((user_id . 90001) (nickname . "Me")))
       (raw_message . "")
       (message . ()))))
   (should (qq-state-message-recalled-p
            (car (qq-state-session-messages "private:10001"))))))

(ert-deftest qq-state-live-dataline-message-routes-by-peer-uid ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (chat_type . 8)
      (peer_uid . "device-1")
      (peer_uin . "0")
      (peer_name . "我的手机")
      (message_id . 123)
      (user_id . 0)
      (time . 1710000001)
      (sender . ((user_id . 0)
                 (nickname . "我的手机")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let* ((session (qq-state-session "dataline:device-1"))
          (message (car (qq-state-session-messages "dataline:device-1"))))
     (should (equal (alist-get 'title session) "我的手机"))
     (should (equal (alist-get 'sender-name message) "我的手机"))
     (should-not (alist-get 'self-p message))
     (should (= (alist-get 'unread-count session) 1)))))

(ert-deftest qq-state-live-service-message-routes-by-peer-uid ()
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (chat_type . 103)
      (peer_uid . "u_mail")
      (peer_uin . "90002")
      (peer_name . "QQ邮箱提醒")
      (message_id . "9007199254747004845")
      (user_id . 90002)
      (time . 1710000100)
      (sender . ((user_id . 90002)
                 (nickname . "QQ邮箱提醒")))
      (raw_message . "[CQ:mail]")
      (message . (((type . "mail")
                   (data . ((sender . "Henrik Lissner")
                            (subject . "Re: Doom Emacs")
                            (prompt . "Henrik Lissner: Re: Doom Emacs"))))))))
   (let* ((session (qq-state-session "service:u_mail"))
          (message (car (qq-state-session-messages "service:u_mail"))))
     (should (equal (alist-get 'title session) "QQ邮箱提醒"))
     (should (equal (alist-get 'preview message)
                    "Henrik Lissner: Re: Doom Emacs"))
     (should (= (alist-get 'unread-count session) 1)))))

(ert-deftest qq-state-mail-segment-preview-prefers-protocol-prompt ()
  (should
   (equal
    (qq-state-message-preview-from-segments
     '(((type . "mail")
        (data . ((sender . "Henrik Lissner")
                 (subject . "Re: Doom Emacs")
                 (prompt . "Henrik Lissner: Re: Doom Emacs"))))))
    "Henrik Lissner: Re: Doom Emacs")))

(ert-deftest qq-state-card-segment-preview-prefers-protocol-prompt ()
  (should
   (equal
    (qq-state-message-preview-from-segments
     '(((type . "card")
        (data . ((kind . "share")
                 (title . "Article")
                 (prompt . "[分享]Article"))))))
    "[分享]Article")))

(ert-deftest qq-state-live-message-ignores-empty-group-card-when-choosing-sender-name ()
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "group")
      (message_id . 123)
      (group_id . 20001)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (card . "")
                 (nickname . "Alice")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "group:20001"))))
     (should (equal (alist-get 'sender-name message) "Alice"))
     (should-not (alist-get 'sender-secondary-name message)))))

(ert-deftest qq-state-group-message-keeps-card-and-nickname-for-display ()
  (qq-test-with-reset
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "group")
      (message_id . 123)
      (group_id . 20001)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (card . "Alice Card")
                 (nickname . "Alice Nick")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "group:20001"))))
     (should (equal (alist-get 'sender-name message) "Alice Card"))
     (should (equal (alist-get 'sender-secondary-name message) "Alice Nick"))
     (should (equal (alist-get 'sender-card message) "Alice Card"))
     (should (equal (alist-get 'sender-nickname message) "Alice Nick")))))

(ert-deftest qq-state-private-message-prefers-remark-and-keeps-nickname-trail ()
  (qq-test-with-reset
   (qq-state-apply-friends
    '(((user_id . 10001)
       (remark . "Alice Remark")
       (nickname . "Alice Nick"))))
   (qq-state-merge-live-message
    '((post_type . "message")
      (message_type . "private")
      (message_id . 123)
      (user_id . 10001)
      (time . 1710000001)
      (sender . ((user_id . 10001)
                 (nickname . "Alice Nick")))
      (raw_message . "hello")
      (message . (((type . "text")
                   (data . ((text . "hello"))))))))
   (let ((message (car (qq-state-session-messages "private:10001"))))
     (should (equal (alist-get 'sender-name message) "Alice Remark"))
     (should (equal (alist-get 'sender-secondary-name message) "Alice Nick"))
     (should (equal (alist-get 'sender-remark message) "Alice Remark"))
     (should (equal (alist-get 'sender-nickname message) "Alice Nick")))))

(ert-deftest qq-state-pending-message-ignores-empty-self-nickname ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "")))
   (let ((message (qq-state-insert-pending-text-message "private:10001" "ping")))
     (should (equal (alist-get 'sender-name message) "90001")))))

(ert-deftest qq-state-insert-pending-message-keeps-segments-and-preview ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-upsert-session "private:10001" '((title . "Alice")) nil)
   (let ((message (qq-state-insert-pending-message
                   "private:10001"
                   '(((type . "reply")
                      (data . ((id . "42"))))
                     ((type . "text")
                      (data . ((text . "hello")))))
                   "hello")))
     (should (equal (alist-get 'raw-message message) "hello"))
     ;; Reply segment is chrome, not body — preview is just the text.
     (should (equal (alist-get 'preview message) "hello"))
     (should (equal (alist-get 'segments message)
                    '(((type . "reply")
                       (data . ((id . "42"))))
                      ((type . "text")
                       (data . ((text . "hello"))))))))))

(ert-deftest qq-state-message-preview-prefers-segments-over-cq-raw ()
  (qq-test-with-reset
   (let ((message
          '((raw-message . "[CQ:image,file=foo.png,url=https://example.com/x]")
            (preview . "[image]")
            (segments . (((type . "image")
                          (data . ((file . "foo.png")
                                   (url . "https://example.com/x")))))))))
     (should (equal (qq-state-message-preview message) "[image]")))))

(ert-deftest qq-state-message-preview-from-cq-strips-reply-and-face ()
  ;; Prefer human face name when qq-media face table is available.
  (should (equal
           (qq-state-message-preview-from-cq
            "[CQ:reply,id=9007199254746000940][CQ:face,id=178,raw={\"faceIndex\":178&#44;\"faceText\":null}]hi")
           (concat (if (fboundp 'qq-media-face-text-fallback)
                       (qq-media-face-text-fallback "178")
                     "[face:178]")
                   "hi")))
  (should (equal
           (qq-state-message-preview-from-cq
            "[CQ:image,file=43DFE.png,url=http://example.com/a.png]")
           "[image]")))

(ert-deftest qq-state-message-preview-falls-back-to-cq-when-no-segments ()
  (qq-test-with-reset
   (let ((message
          '((raw-message . "[CQ:face,id=178]ok")
            (segments . nil)
            (preview . ""))))
     (should (equal (qq-state-message-preview message)
                    (concat (if (fboundp 'qq-media-face-text-fallback)
                                (qq-media-face-text-fallback "178")
                              "[face:178]")
                            "ok"))))))

(ert-deftest qq-state-apply-recent-contacts-does-not-surface-cq ()
  (qq-test-with-reset
   (qq-state-apply-recent-contacts
    '(((chatType . 1)
       (peerUin . "10002")
       (remark . "Bob")
       (msgTime . "1710000001")
       (msgId . "99")
       (lastestMsg
        (time . 1710000001)
        (message_type . "private")
        (user_id . 10002)
        (raw_message . "[CQ:image,file=x.png,url=http://e/x]")
        (message . (((type . "image")
                     (data . ((file . "x.png")
                              (url . "http://e/x"))))))))))
   (let ((session (qq-state-session "private:10002")))
     (should (equal (alist-get 'last-message-preview session) "[image]")))))

(ert-deftest qq-state-set-status-deduplicates-identical-events ()
  (qq-test-with-reset
   (let (events)
     (add-hook 'qq-state-change-hook
               (lambda (event)
                 (when (eq (plist-get event :type) 'status)
                   (push event events))))
     (qq-state-set-status '((online . t)))
     (qq-state-set-status '((online . t)))
     (qq-state-set-status '((online . nil)))
     (should (= 2 (length events))))))

(ert-deftest qq-state-message-events-include-mutation-metadata ()
  (qq-test-with-reset
   (qq-state-set-self-info '((user_id . 90001)
                             (nickname . "Me")))
   (qq-state-upsert-session "private:10001" '((title . "Alice")) nil)
   (let (events)
     (add-hook 'qq-state-change-hook
               (lambda (event)
                 (when (memq (plist-get event :type) '(message history session))
                   (push event events))))
     (let* ((pending (qq-state-insert-pending-text-message "private:10001" "ping"))
            (local-id (alist-get 'local-id pending))
            (snowflake "9007199254741004645")
            (create-event (car events)))
       (should (eq (plist-get create-event :type) 'message))
       (should (eq (plist-get create-event :mutation) 'create))
       (should (eq (plist-get create-event :source) 'local))
       (should (equal (plist-get create-event :message-anchor) local-id))
       (setq events nil)
       (qq-state-mark-pending-message-sent "private:10001" local-id snowflake)
       (let ((sent-event (car events)))
         (should (eq (plist-get sent-event :mutation) 'update))
         (should (eq (plist-get sent-event :source) 'response))
         (should (equal (plist-get sent-event :previous-anchor) local-id))
         (should (equal (plist-get sent-event :message-anchor) snowflake)))
       (setq events nil)
       (qq-state-merge-live-message
        '((post_type . "message")
          (message_type . "private")
          (message_id . "9007199254741004999")
          (user_id . 10001)
          (time . 1710000099)
          (sender . ((user_id . 10001)
                     (nickname . "Alice")))
          (raw_message . "hello")
          (message . (((type . "text")
                       (data . ((text . "hello"))))))))
       (let ((live-event (car events)))
         (should (eq (plist-get live-event :mutation) 'create))
         (should (eq (plist-get live-event :source) 'event))
         (should (equal (plist-get live-event :message-anchor)
                        "9007199254741004999")))
       (setq events nil)
       (qq-state-apply-recall "9007199254741004999")
       (let ((recall-event (car events)))
         (should (eq (plist-get recall-event :mutation) 'update))
         (should (eq (plist-get recall-event :source) 'notice))
         (should (equal (plist-get recall-event :message-anchor)
                        "9007199254741004999")))
       (setq events nil)
       (qq-state-merge-history
        "private:10001"
        (list
         '((message_id . "9007199254741004001")
           (message_type . "private")
           (user_id . 10001)
           (time . 1710000001)
           (sender . ((user_id . 10001)
                      (nickname . "Alice")))
           (raw_message . "older")
           (message . (((type . "text")
                        (data . ((text . "older")))))))))
       (let ((history-event (car events)))
         (should (eq (plist-get history-event :type) 'history))
         (should (eq (plist-get history-event :mutation) 'history))
         (should (= (plist-get history-event :message-count) 1))
         (should (= (plist-get history-event :added-count) 1)))
       (setq events nil)
       (qq-state-clear-session-unread "private:10001")
       (let ((read-event (car events)))
         (should (eq (plist-get read-event :type) 'session))
         (should (eq (plist-get read-event :mutation) 'read)))
       (setq events nil)
       (qq-state-set-session-unread "private:10001" 4)
       (let ((restore-event (car events)))
         (should (eq (plist-get restore-event :mutation) 'read))
         (should (= 4 (alist-get 'unread-count
                                 (qq-state-session "private:10001")))))))))

(ert-deftest qq-state-merge-history-added-count-skips-duplicates ()
  (let ((qq-state-change-hook nil)
        meta)
    (qq-state-reset)
    (qq-state-upsert-session "private:10001" '((target-id . "10001")) nil)
    (qq-state-merge-history
     "private:10001"
     (list
      '((message_id . "100")
        (message_type . "private")
        (user_id . 10001)
        (time . 1710000001)
        (sender . ((user_id . 10001) (nickname . "A")))
        (raw_message . "a")
        (message . (((type . "text") (data . ((text . "a")))))))))
    (setq meta
          (qq-state-merge-history
           "private:10001"
           (list
            '((message_id . "100")
              (message_type . "private")
              (user_id . 10001)
              (time . 1710000001)
              (sender . ((user_id . 10001) (nickname . "A")))
              (raw_message . "a")
              (message . (((type . "text") (data . ((text . "a")))))))
            '((message_id . "90")
              (message_type . "private")
              (user_id . 10001)
              (time . 1710000000)
              (sender . ((user_id . 10001) (nickname . "A")))
              (raw_message . "older")
              (message . (((type . "text") (data . ((text . "older"))))))))))
    (should (= (plist-get meta :message-count) 2))
    (should (= (plist-get meta :added-count) 1))
    (should (equal (plist-get meta :oldest-message-id) "90"))
    (should (= (length (qq-state-session-messages "private:10001")) 2))))

(provide 'qq-state-test)

;;; qq-state-test.el ends here
