;;; qq-user-test.el --- Tests for qq-user -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'qq-user)
(require 'qq-user-photo)
(require 'qq-chat)
(require 'qq-root)

(defconst qq-user-test--profile
  '((user_id . "10001")
    (nickname . "Alice")
    (remark . "A")
    (signature . "hello from Emacs")
    (qid . "alice")
    (sex . "female")
    (age . 26)
    (birthday . ((year . 2000) (month . 7) (day . 10)))
    (location . ((country . "中国") (province . "上海") (city)))
    (occupation . "Engineer")
    (college . "Example University")
    (labels . ("Emacs" "QQ"))
    (status . ((code . 10) (extended_code . 0) (description . "在线")))
    (relationship . ((kind . "friend")
                     (blocked_by_me . :false)
                     (special_care . t)
                     (muted . t)
                     (friend_category . ((id . 7) (name . "Friends")))))
    (qq_level . ((stars . 1) (moons . 2) (suns . 3) (crowns . 4)))
    (vip . ((kind . "svip") (level . 8) (annual . t))))
  "One complete native profile fixture.")

(ert-deftest qq-api-get-user-sends-string-identity ()
  (let (action params value)
    (cl-letf (((symbol-function 'qq-api-call)
               (lambda (candidate-action candidate-params callback
                        &optional _errback)
                 (setq action candidate-action
                       params candidate-params)
                 (funcall callback `((data . ,qq-user-test--profile)))
                 'request)))
      (should (eq (qq-api-get-user "10001" (lambda (profile)
                                              (setq value profile)))
                  'request))
      (should (equal action "emacs_get_user"))
      (should (equal params '((user_id . "10001"))))
      (should (equal (alist-get 'user_id value) "10001"))
      (should-error (qq-api-get-user 10001 #'ignore) :type 'user-error))))

(ert-deftest qq-user-render-shows-telega-style-profile-card ()
  (with-temp-buffer
    (qq-user-mode)
    (setq qq-user--user-id "10001"
          qq-user--profile (copy-tree qq-user-test--profile)
          qq-user--like-count 42
          qq-user--photo-loaded t
          qq-user--photos
          '(((id . "p1")
             (original_url . "https://example.test/p1.jpg")
             (thumbnail_url . "https://example.test/p1-thumb.jpg"))))
    (cl-letf (((symbol-function 'qq-media-avatar-display-string)
               (lambda (_user-id) "@"))
              ((symbol-function 'qq-user-photo-preview-display-string)
               (lambda (_user-id _photo fallback) fallback)))
      (qq-user-render))
    (let ((text (buffer-string)))
      (should (string-match-p "A" text))
      (should (string-match-p "QQ:[[:space:]]+10001" text))
      (should (string-match-p "特别关心" text))
      (should (string-match-p "消息免打扰" text))
      (should (string-match-p "分组:[[:space:]]+Friends" text))
      (should (string-match-p "获赞:[[:space:]]+42" text))
      (should (string-match-p "照片墙:[[:space:]]+1" text))
      (should (string-match-p "SVIP 8" text))
      (should (string-match-p "hello from Emacs" text))
      (should-not (string-match-p "\\[Open\\]" text))
      (goto-char (point-min))
      (search-forward "发消息")
      (should (button-at (1- (point))))
      (search-forward "照片 1")
      (should (button-at (1- (point)))))))

(ert-deftest qq-user-render-omits-private-placeholder-values ()
  (with-temp-buffer
    (qq-user-mode)
    (setq qq-user--user-id "10001"
          qq-user--profile
          '((user_id . "10001")
            (nickname . "Alice")
            (sex . "unknown")
            (age)
            (status . ((code . 99) (description)))
            (relationship . ((kind . "friend")))
            (qq_level)
            (vip)
            (registered_at . 123456)))
    (cl-letf (((symbol-function 'qq-media-avatar-display-string)
               (lambda (_user-id) "@")))
      (qq-user-render))
    (let ((text (buffer-string)))
      (should (string-match-p "关系:[[:space:]]+好友" text))
      (should-not (string-match-p "状态:" text))
      (should-not (string-match-p "年龄:" text))
      (should-not (string-match-p "性别:" text))
      (should-not (string-match-p "等级:" text))
      (should-not (string-match-p "会员:" text))
      (should-not (string-match-p "注册:" text)))))

(ert-deftest qq-user-refresh-handles-synchronous-response-ownership ()
  (with-temp-buffer
    (qq-user-mode)
    (setq qq-user--user-id "10001")
    (cl-letf (((symbol-function 'qq-user-render) #'ignore)
              ((symbol-function 'qq-api-get-user)
               (lambda (_user-id callback &optional _errback)
                 (funcall callback (copy-tree qq-user-test--profile))
                 'request))
              ((symbol-function 'qq-api-get-user-like)
               (lambda (_user-id callback &optional _errback)
                 (funcall callback 42)
                 'like-request))
              ((symbol-function 'qq-api-get-user-photo-wall)
               (lambda (_user-id callback &optional _errback)
                 (funcall callback nil)
                 'photo-request)))
      (qq-user-refresh)
      (should (equal qq-user--profile qq-user-test--profile))
      (should (= qq-user--like-count 42))
      (should qq-user--photo-loaded)
      (should-not qq-user--loading)
      (should-not qq-user--request)
      (should-not qq-user--request-owner))))

(ert-deftest qq-chat-open-user-at-point-uses-sender-id ()
  (let (opened)
    (cl-letf (((symbol-function 'qq-chat--message-at-point)
               (lambda () '((sender-id . "10001"))))
              ((symbol-function 'qq-user-open)
               (lambda (user-id) (setq opened user-id))))
      (qq-chat-open-user-at-point)
      (should (equal opened "10001")))))

(ert-deftest qq-root-open-user-at-point-requires-private-session ()
  (let (opened)
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . private)
                            (target-id . "10001"))))
              ((symbol-function 'qq-user-open)
               (lambda (user-id) (setq opened user-id))))
      (qq-root-open-user-at-point)
      (should (equal opened "10001")))
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . group)
                            (target-id . "20001")))))
      (should-error (qq-root-open-user-at-point) :type 'user-error))))

(ert-deftest qq-user-entry-keymaps-are-discoverable ()
  (should (eq (lookup-key qq-chat-timeline-mode-map (kbd "i"))
              #'qq-chat-open-user-at-point))
  (should (eq (lookup-key qq-root-mode-map (kbd "i"))
              #'qq-root-open-info-at-point))
  (should (eq (lookup-key qq-user-mode-map (kbd "m"))
              #'qq-user-open-chat))
  (should (eq (lookup-key qq-user-mode-map (kbd "p"))
              #'qq-user-open-photo-wall)))

(ert-deftest qq-user-reuses-one-profile-buffer-like-telega ()
  (should (equal (qq-user--buffer-name "10001") "*qq-user*"))
  (should (equal (qq-user--buffer-name "10002") "*qq-user*")))

(ert-deftest qq-api-get-user-social-actions-preserve-string-identity ()
  (let (calls like photos)
    (cl-letf (((symbol-function 'qq-api-call)
               (lambda (action params callback &optional _errback)
                 (push (list action params) calls)
                 (funcall
                  callback
                  (pcase action
                    ("emacs_get_user_like"
                     '((data . ((user_id . "10001") (total_count . 42)))))
                    ("emacs_get_user_photo_wall"
                     '((data . ((user_id . "10001")
                                (photos . (((id . "p1")
                                            (original_url . "https://example.test/p1.jpg")
                                            (thumbnail_url))))))))))
                 'request)))
      (qq-api-get-user-like "10001" (lambda (count) (setq like count)))
      (qq-api-get-user-photo-wall "10001" (lambda (value) (setq photos value))))
    (should (= like 42))
    (should (equal (alist-get 'id (car photos)) "p1"))
    (should (member '("emacs_get_user_like" ((user_id . "10001"))) calls))
    (should (member '("emacs_get_user_photo_wall" ((user_id . "10001"))) calls))))

(ert-deftest qq-user-photo-render-has-no-inline-open-button ()
  (with-temp-buffer
    (qq-user-photo-mode)
    (setq qq-user-photo--user-id "10001"
          qq-user-photo--photos
          '(((id . "p1")
             (original_url . "https://example.test/p1.jpg")
             (thumbnail_url . "https://example.test/p1-thumb.jpg"))))
    (cl-letf (((symbol-function 'qq-media-url-preview-display-string)
               (lambda (_key _url fallback) fallback)))
      (qq-user-photo-render))
    (should (string-match-p "Photo 1" (buffer-string)))
    (should-not (string-match-p "\\[Open\\]" (buffer-string)))
    (should-not (string-match-p "g refresh" (buffer-string)))
    (goto-char (point-min))
    (search-forward "Photo 1")
    (should (equal (alist-get 'id (qq-user-photo--photo-at-point)) "p1"))))

(provide 'qq-user-test)

;;; qq-user-test.el ends here
