;;; qq-user-test.el --- Tests for qq-user -*- lexical-binding: t; -*-

;;; Code:

(require 'ert)
(require 'cl-lib)
(require 'qq-user)
(require 'qq-chat)
(require 'qq-root)

(defconst qq-user-test--profile
  '((user_id . "10001")
    (nickname . "Alice")
    (remark . "A")
    (signature . "hello from Emacs")
    (qid . "alice")
    (sex . "female")
    (age . 26)
    (birthday . ((year . 2000) (month . 7) (day . 10)))
    (location . ((country . "中国") (province . "上海") (city)))
    (occupation . "Engineer")
    (college . "Example University")
    (registered_at . 123456)
    (labels . ("Emacs" "QQ"))
    (status . ((code . 10) (extended_code . 0) (description . "在线")))
    (relationship . ((kind . "friend")
                     (blocked_by_me . :false)
                     (special_care . t)))
    (qq_level . ((stars . 1) (moons . 2) (suns . 3) (crowns . 4)))
    (vip . ((kind . "svip") (level . 8) (annual . t))))
  "One complete native profile fixture.")

(ert-deftest qq-api-get-user-sends-string-identity ()
  (let (action params value)
    (cl-letf (((symbol-function 'qq-api-call)
               (lambda (candidate-action candidate-params callback
                        &optional _errback)
                 (setq action candidate-action
                       params candidate-params)
                 (funcall callback `((data . ,qq-user-test--profile)))
                 'request)))
      (should (eq (qq-api-get-user "10001" (lambda (profile)
                                              (setq value profile)))
                  'request))
      (should (equal action "emacs_get_user"))
      (should (equal params '((user_id . "10001"))))
      (should (equal (alist-get 'user_id value) "10001"))
      (should-error (qq-api-get-user 10001 #'ignore) :type 'user-error))))

(ert-deftest qq-user-render-shows-profile-without-action-buttons ()
  (with-temp-buffer
    (qq-user-mode)
    (setq qq-user--user-id "10001"
          qq-user--profile (copy-tree qq-user-test--profile))
    (cl-letf (((symbol-function 'qq-media-avatar-display-string)
               (lambda (_user-id) "@")))
      (qq-user-render))
    (let ((text (buffer-string)))
      (should (string-match-p "A" text))
      (should (string-match-p "QQ:[[:space:]]+10001" text))
      (should (string-match-p "特别关心" text))
      (should (string-match-p "SVIP 8" text))
      (should (string-match-p "hello from Emacs" text))
      (should-not (string-match-p "\\[Open\\]" text))
      (should-not (button-at (point-min))))))

(ert-deftest qq-user-refresh-handles-synchronous-response-ownership ()
  (with-temp-buffer
    (qq-user-mode)
    (setq qq-user--user-id "10001")
    (cl-letf (((symbol-function 'qq-user-render) #'ignore)
              ((symbol-function 'qq-api-get-user)
               (lambda (_user-id callback &optional _errback)
                 (funcall callback (copy-tree qq-user-test--profile))
                 'request)))
      (qq-user-refresh)
      (should (equal qq-user--profile qq-user-test--profile))
      (should-not qq-user--loading)
      (should-not qq-user--request)
      (should-not qq-user--request-owner))))

(ert-deftest qq-chat-open-user-at-point-uses-sender-id ()
  (let (opened)
    (cl-letf (((symbol-function 'qq-chat--message-at-point)
               (lambda () '((sender-id . "10001"))))
              ((symbol-function 'qq-user-open)
               (lambda (user-id) (setq opened user-id))))
      (qq-chat-open-user-at-point)
      (should (equal opened "10001")))))

(ert-deftest qq-root-open-user-at-point-requires-private-session ()
  (let (opened)
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . private)
                            (target-id . "10001"))))
              ((symbol-function 'qq-user-open)
               (lambda (user-id) (setq opened user-id))))
      (qq-root-open-user-at-point)
      (should (equal opened "10001")))
    (cl-letf (((symbol-function 'qq-root--session-at-point)
               (lambda () '((type . group)
                            (target-id . "20001")))))
      (should-error (qq-root-open-user-at-point) :type 'user-error))))

(ert-deftest qq-user-entry-keymaps-are-discoverable ()
  (should (eq (lookup-key qq-chat-timeline-mode-map (kbd "i"))
              #'qq-chat-open-user-at-point))
  (should (eq (lookup-key qq-root-mode-map (kbd "i"))
              #'qq-root-open-user-at-point))
  (should (eq (lookup-key qq-user-mode-map (kbd "m"))
              #'qq-user-open-chat)))

(provide 'qq-user-test)

;;; qq-user-test.el ends here
